---
# tasks file for webserver]
- name: install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - docker.io
    - python-pip

- name: Install docker-py
  pip:
    name: docker-py

- name: pull an image
  docker_image:
   name: {{ NexSrvIp }}:{{ NexSrvIpPrt }}/mavtom:v1
