---
# tasks file for buildserver
- name: install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - docker.io
    - python-pip

- name: Install docker-py
  pip:
    name: docker-py

- name: Copy Dockerfile
    copy: src=Dockerfile dest={{ dest_folder }}/Dockerfile

- name: Build an image and push it to a private repo
  docker_image:
      path: /home/dockerfile/
      name: {{ NexSrvIp }}:{{ NexSrvIpPrt }}/mavtom
      tag: v1
      push: yes
